<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <!--[if !mso]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en-us" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="date=no" />
    <meta name="format-detection" content="address=no" />
    <meta name="format-detection" content="email=no" />
    <title>Account recent Leads</title>
    <style type="text/css">
        .ExternalClass {
            width: 100%;
            background: inherit;
            background-color: inherit;
        }

        .ExternalClass p,
        .ExternalClass ul,
        .ExternalClass ol {
            Margin: 0;
        }

        .undoreset div p,
        .undoreset p {
            margin-bottom: 20px;
        }

        div[class^="aolmail_divbody"] {
            overflow: auto;
        }

        [owa] #ac-footer {
            padding: 20px 0px !important;
            background: inherit;
            background-color: inherit;
        }
    </style>
    <style type="text/css">
        @media only screen and (max-width: 600px) {

            /*-------------------------------------------------------------------------*\ Abandoned Cart widget \*------------------------------------------------------------------------*/
            .td_abandoned-cart img {
                display: block;
                padding-right: 0 !important;
                padding-bottom: 0 !important;
                width: 100% !important;
                max-width: 100% !important;
                height: auto !important;
            }

            body {
                padding: 0 !important;
                font-size: 1em !important;
            }

            * {
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
            }

            *[class].divbody {
                -webkit-text-size-adjust: none !important;
                width: auto !important;
            }

            *[class].td_picture img {
                width: auto !important;
            }

            *[class].td_text {
                line-height: 110%;
            }

            *[class].td_button {
                width: auto;
            }

            /* Collapse all block elements */
            :not(.body) table {
                display: block !important;
                float: none !important;
                border-collapse: collapse !important;
                width: 100% !important;
                min-width: 100% !important;
                clear: both !important;
            }

            :not(.body) thead,
            :not(.body) tbody,
            :not(.body) tr {
                display: block !important;
                float: none !important;
                width: 100% !important;
            }

            :not(.body) th,
            :not(.body) td,
            :not(.body) p {
                display: block !important;
                float: none !important;
                width: 100% !important;
                clear: both !important;
            }

            /* Remove browser default styling for elements */
            ul,
            ol {
                margin-left: 20px;
                margin-bottom: 10px;
                margin-top: 10px;
                -webkit-margin-before: 0;
                -webkit-margin-after: 0;
                -webkit-padding-start: 0;
            }

            /* Set default height for spacer once collapse */
            *[class].spacer {
                height: auto !important;
            }

            a[href^=date] {
                color: inherit !important;
                text-decoration: none !important;
            }

            a[href^=telephone] {
                color: inherit !important;
                text-decoration: none !important;
            }

            a[href^=address] {
                color: inherit !important;
                text-decoration: none !important;
            }

            a[href^=email] {
                color: inherit !important;
                text-decoration: none !important;
            }

            /* Default table cell height */
            td[height="1"] {
                height: 1px !important;
                font-size: 1px !important;
                line-height: 1px !important;
            }

            td[height="0"] {
                height: 0px !important;
                font-size: 0px !important;
                line-height: 0px !important;
            }

            td[height="12"] {
                height: 12px !important;
                font-size: 12px !important;
                line-height: 12px !important;
            }

            /* Default social icons */
            *[class].ac-social-icon-16 {
                width: 16px !important;
                height: 16px !important;
            }

            *[class].ac-social-icon-24 {
                width: 24px !important;
                height: 24px !important;
            }

            *[class].ac-social-icon-28 {
                width: 28px !important;
                height: 28px !important;
            }

            *[class].__ac_social_icons {
                margin-right: 0px !important;
            }
        }
    </style>
    <style type="text/css">
        @media only screen and (max-width: 320px) {
            #layout-row4070 img {
                width: 100% !important;
                height: auto !important;
                max-width: 320px !important;
            }

            #layout-row4080 img {
                width: 100% !important;
                height: auto !important;
                max-width: 320px !important;
            }

            #layout-row4309 .break-line {
                width: 100% !important;
                margin: auto !important;
            }

            .td_rss .rss-item img.iphone_large_image {
                width: auto !important;
            }

            u+.body {
                display: table !important;
                width: 100vw !important;
                min-width: 100vw !important;
            }

            u+.body table {
                display: table !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body td {
                display: block !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body img {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                vertical-align: bottom !important;
            }

            u+.body center {
                display: block !important;
                margin: auto !important;
                width: 100% !important;
                min-width: 100% !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table,
            u+.body table._ac_social_table td,
            u+.body table._ac_social_table div,
            u+.body table._ac_social_table a {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                min-width: auto !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table img {
                display: inline-block !important;
                margin: auto !important;
                width: 32px !important;
                min-width: 32px !important;
                max-width: 32px !important;
            }
        }

        @media only screen and (max-width: 375px) {
            #layout-row4070 img {
                width: 100% !important;
                height: auto !important;
                max-width: 375px !important;
            }

            #layout-row4080 img {
                width: 100% !important;
                height: auto !important;
                max-width: 375px !important;
            }

            #layout-row4309 .break-line {
                width: 100% !important;
                margin: auto !important;
            }

            .td_rss .rss-item img.iphone_large_image {
                width: auto !important;
            }

            u+.body {
                display: table !important;
                width: 100vw !important;
                min-width: 100vw !important;
            }

            u+.body table {
                display: table !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body td {
                display: block !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body img {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                vertical-align: bottom !important;
            }

            u+.body center {
                display: block !important;
                margin: auto !important;
                width: 100% !important;
                min-width: 100% !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table,
            u+.body table._ac_social_table td,
            u+.body table._ac_social_table div,
            u+.body table._ac_social_table a {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                min-width: auto !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table img {
                display: inline-block !important;
                margin: auto !important;
                width: 32px !important;
                min-width: 32px !important;
                max-width: 32px !important;
            }
        }

        @media only screen and (max-width: 414px) {
            #layout-row4070 img {
                width: 100% !important;
                height: auto !important;
                max-width: 414px !important;
            }

            #layout-row4080 img {
                width: 100% !important;
                height: auto !important;
                max-width: 414px !important;
            }

            #layout-row4309 .break-line {
                width: 100% !important;
                margin: auto !important;
            }

            .td_rss .rss-item img.iphone_large_image {
                width: auto !important;
            }

            u+.body {
                display: table !important;
                width: 100vw !important;
                min-width: 100vw !important;
            }

            u+.body table {
                display: table !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body td {
                display: block !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body img {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                vertical-align: bottom !important;
            }

            u+.body center {
                display: block !important;
                margin: auto !important;
                width: 100% !important;
                min-width: 100% !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table,
            u+.body table._ac_social_table td,
            u+.body table._ac_social_table div,
            u+.body table._ac_social_table a {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                min-width: auto !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table img {
                display: inline-block !important;
                margin: auto !important;
                width: 32px !important;
                min-width: 32px !important;
                max-width: 32px !important;
            }
        }

        @media only screen and (max-width: 667px) {
            #layout-row4070 img {
                width: 100% !important;
                height: auto !important;
                max-width: 667px !important;
            }

            #layout-row4080 img {
                width: 100% !important;
                height: auto !important;
                max-width: 667px !important;
            }

            #layout-row4309 .break-line {
                width: 100% !important;
                margin: auto !important;
            }

            .td_rss .rss-item img.iphone_large_image {
                width: auto !important;
            }

            u+.body {
                display: table !important;
                width: 100vw !important;
                min-width: 100vw !important;
            }

            u+.body table {
                display: table !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body td {
                display: block !important;
                width: 100% !important;
                min-width: 100% !important;
            }

            u+.body img {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                vertical-align: bottom !important;
            }

            u+.body center {
                display: block !important;
                margin: auto !important;
                width: 100% !important;
                min-width: 100% !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table,
            u+.body table._ac_social_table td,
            u+.body table._ac_social_table div,
            u+.body table._ac_social_table a {
                display: inline-block !important;
                margin: auto !important;
                width: auto !important;
                min-width: auto !important;
                text-align: center !important;
            }

            u+.body table._ac_social_table img {
                display: inline-block !important;
                margin: auto !important;
                width: 32px !important;
                min-width: 32px !important;
                max-width: 32px !important;
            }
        }
    </style>
</head>

<body id="ac-designer" class="body" style="font-family: Arial; line-height: 1.1; margin: 0px; background-color: #e7e7e7; width: 100%; text-align: center;">
<div class="divbody" style="margin: 0px; outline: none; padding: 0px; color: #000000; font-family: arial; line-height: 1.1; width: 100%; background-color: #e7e7e7; background: #e7e7e7; text-align: center;">
    <table class="template-table" border="0" cellpadding="0" cellspacing="0" width="100%" align="left" style="font-size: 13px; min-width: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #e7e7e7; background: #e7e7e7;">
        <tr>
            <td align="center" valign="top" width="100%">
                <table class="template-table" border="0" cellpadding="0" cellspacing="0" width="650" bgcolor="#e7e7e7" style="font-size: 13px; min-width: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; max-width: 650px;">
                    <tr>
                        <td id="layout_table_0a1a232be98a04ef37895cc3b95e9c947310bbaa" valign="top" align="center" width="650" style="background-color: #ffffff;">
                            <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table root-table" width="650" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;">
                                <tr style="background-color: #ffffff;">
                                    <td id="layout-row-margin4070" valign="top" style="padding: 30px 20px 30px 20px; background-color: #ffffff;">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                            <tr id="layout-row4070" class="layout layout-row widget _widget_picture style4070" align="center" style="background-color: #ffffff;">
                                                <td id="layout-row-padding4070" valign="top" style="background-color: #ffffff; padding: 0px;">
                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td class="image-td" align="center" valign="top" width="610">
                                                                <a href="${SUB_DOMAIN_CMS}" style="margin: 0; outline: none; padding: 0; color: #045fb4; display: block; min-width: 100%;">
                                                                    <img src="${LOGO}" alt="" width="290" style="border: none; display: block; outline: none; width: 290px; opacity: 1; max-width: 100%;" />
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr style="background-color: #ffffff;">
                                    <td valign="top" style="padding: 40px; background-color: #ffffff;">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                            <tr id="layout-row4073" class="layout layout-row widget _widget_text style4073" style="margin: 0; padding: 0; background-color: #ffffff;">
                                                <td id="layout-row-padding4073" valign="top" style="background-color: #ffffff; padding: 0px;">
                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td id="text_div3448" class="td_text td_block" valign="top" align="left" style="line-height: 150%; color: inherit; font-size: 12px; font-weight: inherit; line-height: 1.5; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly;">
                                                                <div style="line-height: 150%; margin: 0; outline: none; padding: 0; font-size: 28px; mso-line-height-rule: exactly; line-height: 1.5;" class="">
                                                                    <div style="margin: 0; outline: none; padding: 0;" class="">
                                                                        <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                            <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                                <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                                    <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                                        <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                                            <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                                                <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                                                    <p style="margin: 0; outline: none; padding: 0; color: #000000; font-size: inherit; font-weight: inherit; line-height: inherit; text-decoration: inherit; text-align: left;" class=""><span style="color: inherit; font-size: inherit; font-weight: 700; line-height: inherit; text-decoration: inherit; font-family: Helvetica, Arial, sans-serif;" class="">Summary of Your Lead Results</span></p>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr id="layout-row4273" class="layout layout-row clear-this " style="background-color: #ffffff;">
                                    <td id="layout-row-padding4273" valign="top" style="background-color: #ffffff;">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                            <tr>
                                                <td id="layout_table_26b3c49aac1453e94a8d2e0fd0a4c5efc050de46" valign="top" width="40" style="background-color: #ffffff;">
                                                    <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table" width="40" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;">
                                                        <tr style="background-color: #ffffff;">
                                                            <td id="layout-row-margin4272" valign="top" style="padding: 0px; background-color: #ffffff;">
                                                                <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                                                    <tr id="layout-row4272" class="layout layout-row widget _widget_spacer style4272" style="">
                                                                        <td id="layout-row-padding4272" valign="top" style="padding: 0;">
                                                                            <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                <tr>
                                                                                    <td valign="top" height="50">
                                                                                        <div class="spacer" style="margin: 0; outline: none; padding: 0; height: 50px;">
                                                                                            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                                <tbody>
                                                                                                <tr>
                                                                                                    <td class="spacer-body" valign="top" height="50" width="40"> </td>
                                                                                                </tr>
                                                                                                </tbody>
                                                                                            </table>
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                            </table>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td id="layout_table_6d9a5328339a7ddee02c286308ef6987b40ab1f2" valign="top" width="601">
                                                    <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table " width="601" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr id="layout-row4275" class="layout layout-row clear-this ">
                                                            <td id="layout-row-padding4275" valign="top">
                                                                <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                    <tr>
                                                                        <td id="layout_table_d0b95bfb0e99d2160534fbbe7be61b477d9ee4c5" valign="top" width="552" style="background-color: #ffffff;">
                                                                            <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table " width="552" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;">
                                                                                <tr style="background-color: #ffffff;">
                                                                                    <td id="layout-row-margin4074" valign="top" style="padding: 24px 0px; background-color: #ffffff;">
                                                                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                                                                            <tr id="layout-row4074" class="layout layout-row widget _widget_text style4074" style="margin: 0; padding: 0;">
                                                                                                <td id="layout-row-padding4074" valign="top" style="padding: 0px;">
                                                                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                                        <tr>
                                                                                                            <td id="text_div3449" class="td_text td_block" valign="top" align="left" style="line-height: 150%; color: inherit; font-size: 12px; font-weight: inherit; line-height: 1.5; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly;">
                                                                                                                <div style="line-height: 150%; margin: 0; outline: none; padding: 0; mso-line-height-rule: exactly; line-height: 1.5;" class="">
                                                                                                                    <p class="" style="margin: 0; outline: none; padding: 0; color: inherit; font-size: 15px; font-weight: inherit; line-height: inherit; text-decoration: inherit;">
                                                                                                                        Here's how your lead campaign has been performing over the last 6 hours.
                                                                                                                    </p>
                                                                                                                    <p class="" style="margin: 0; outline: none; padding: 0; color: inherit; font-size: 15px; font-weight: inherit; line-height: inherit; text-decoration: inherit;">
                                                                                                                        Good luck with your prospecting, go get them!
                                                                                                                    </p>
                                                                                                                </div>
                                                                                                            </td>
                                                                                                        </tr>
                                                                                                    </table>
                                                                                                </td>
                                                                                            </tr>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </table>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td id="layout_table_26b3c49aac1453e94a8d2e0fd0a4c5efc050de46" valign="top" width="40" style="background-color: #ffffff;">
                                                    <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table " width="40" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;">
                                                        <tr style="background-color: #ffffff;">
                                                            <td id="layout-row-margin4272" valign="top" style="padding: 0px; background-color: #ffffff;">
                                                                <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                                                    <tr id="layout-row4272" class="layout layout-row widget _widget_spacer style4272" style="">
                                                                        <td id="layout-row-padding4272" valign="top" style="padding: 0;">
                                                                            <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                <tr>
                                                                                    <td valign="top" height="50">
                                                                                        <div class="spacer" style="margin: 0; outline: none; padding: 0; height: 50px;">
                                                                                            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                                <tbody>
                                                                                                <tr>
                                                                                                    <td class="spacer-body" valign="top" height="50" width="40"> </td>
                                                                                                </tr>
                                                                                                </tbody>
                                                                                            </table>
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                            </table>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td id="layout_table_6d9a5328339a7ddee02c286308ef6987b40ab1f2" valign="top" width="601">
                                                    <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table " width="601" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr id="layout-row4275" class="layout layout-row clear-this ">
                                                            <td id="layout-row-padding4275" valign="top">
                                                                <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                    <tr>
                                                                        <td id="layout_table_d0b95bfb0e99d2160534fbbe7be61b477d9ee4c5" valign="top" width="552" style="background-color: #ffffff;">
                                                                            <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table " width="552" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;">
                                                                                <tr style="background-color: #ffffff;">
                                                                                    <td id="layout-row-margin4074" valign="top" style="padding: 24px 0px; background-color: #ffffff;">
                                                                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                                                                            <tr id="layout-row4074" class="layout layout-row widget _widget_text style4074" style="margin: 0; padding: 0;">
                                                                                                <td valign="top" style="padding: 0px;">
                                                                                                    <table width="364px" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                                        <tr>
                                                                                                            <td id="text_div3449" class="td_text td_block" valign="top" align="center" style="line-height: 150%; color: inherit; font-size: 12px; font-weight: inherit; line-height: 1.5; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly; padding: 12px; border: 1px solid #979797;">
                                                                                                                <span style="font-size: 18px">New Leads</span>
                                                                                                            </td>
                                                                                                        </tr>
                                                                                                        <tr>
                                                                                                            <td class="td_text td_block" valign="top" align="center" style="line-height: 150%; color: inherit; font-weight: inherit; line-height: 1.5; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly; padding: 30px; border: 1px solid #979797; border-top: none;">
                                                                                                                <p style="font-size: 40px; font-weight: bold; margin: 0; margin-bottom: 12px; color: ${PRIMARY_COLOR}">${NEW_LEADS}</p>
                                                                                                                <span style="font-weight: lighter">Lead${(NEW_LEADS > 1)?then('s','')} added over the last 6 hours</span>
                                                                                                            </td>
                                                                                                        </tr>
                                                                                                    </table>
                                                                                                </td>
                                                                                                <td style="padding: 0px;">
                                                                                                    <div style="width: 40px;"></div>
                                                                                                </td>
                                                                                                <td valign="top" style="padding: 0px;">
                                                                                                    <table width="364px" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                                        <tr>
                                                                                                            <td id="text_div3449" class="td_text td_block" valign="top" align="center" style="line-height: 150%; color: inherit; font-size: 12px; font-weight: inherit; line-height: 1.5; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly; padding: 12px; border: 1px solid #979797;">
                                                                                                                <span style="font-size: 18px">Total Leads</span>
                                                                                                            </td>
                                                                                                        </tr>
                                                                                                        <tr>
                                                                                                            <td class="td_text td_block" valign="top" align="center" style="line-height: 150%; color: inherit; font-weight: inherit; line-height: 1.5; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly; padding: 30px; border: 1px solid #979797; border-top: none;">
                                                                                                                <p style="font-size: 40px; font-weight: bold; margin: 0; margin-bottom: 12px; color: ${PRIMARY_COLOR}">${TOTAL_LEADS}</p>
                                                                                                                <span style="font-weight: lighter">Lead${(TOTAL_LEADS > 1)?then('s','')} you have in your account</span>
                                                                                                            </td>
                                                                                                        </tr>
                                                                                                    </table>
                                                                                                </td>
                                                                                            </tr>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </table>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td id="layout_table_26b3c49aac1453e94a8d2e0fd0a4c5efc050de46" valign="top" width="40" style="background-color: #ffffff;">
                                                    <table cellpadding="0" cellspacing="0" border="0" class="layout layout-table " width="40" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;">
                                                        <tr style="background-color: #ffffff;">
                                                            <td id="layout-row-margin4272" valign="top" style="padding: 0px; background-color: #ffffff;">
                                                                <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                                                    <tr id="layout-row4272" class="layout layout-row widget _widget_spacer style4272" style="">
                                                                        <td id="layout-row-padding4272" valign="top" style="padding: 0;">
                                                                            <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                <tr>
                                                                                    <td valign="top" height="50">
                                                                                        <div class="spacer" style="margin: 0; outline: none; padding: 0; height: 50px;">
                                                                                            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                                                <tbody>
                                                                                                <tr>
                                                                                                    <td class="spacer-body" valign="top" height="50" width="40"> </td>
                                                                                                </tr>
                                                                                                </tbody>
                                                                                            </table>
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                            </table>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <#if RECENT_CAMPAIGN_ROWS?has_content>
                                <tr style="background-color: #FFFFFF;">
                                    <td valign="top" style="padding: 0px 40px; background-color: #FFFFFF;">
                                        <div style="background-color: #979797; height: 1px; width: 100%;"></div>
                                    </td>
                                </tr>
                                <tr style="background-color: #FFFFFF;">
                                    <td valign="top" style="padding: 24px 40px; background-color: #FFFFFF;">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                            <tr id="layout-row4073" class="layout layout-row widget _widget_text style4073" style="margin: 0; padding: 0; background-color: #ffffff;">
                                                <td id="layout-row-padding4073" valign="top" style="background-color: #ffffff; padding: 0px;">
                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td id="text_div3448" class="td_text td_block" valign="top" align="left" style="line-height: 150%; color: inherit; font-size: 12px; font-weight: inherit; line-height: 1.5; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly;">
                                                                <div style="line-height: 150%; margin: 0; outline: none; padding: 0; font-size: 28px; mso-line-height-rule: exactly; line-height: 1.5;" class="">
                                                                    <div style="margin: 0; outline: none; padding: 0;" class="">
                                                                        <div style="margin: 0; outline: none; padding: 0; color: #000000;" class="">
                                                                            <p style="margin: 0; outline: none; padding: 0; color: #000000; font-size: inherit; font-weight: inherit; line-height: inherit; text-decoration: inherit; text-align: left;" class=""><span style="color: inherit; font-size: inherit; font-weight: 700; line-height: inherit; text-decoration: inherit; font-family: Helvetica, Arial, sans-serif;" class="">Campaign Breakdown</span></p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr style="background-color: #ffffff;">
                                    <td valign="top" style="padding: 0px 40px; background-color: #ffffff;">
                                        <p style="margin: 0; outline: none; padding: 0; color: #000000; font-size: inherit; font-weight: inherit; line-height: inherit; text-decoration: inherit; text-align: left;" class="">
                                            <span style="color: inherit; font-size: 16px; font-weight: normal; line-height: inherit; text-decoration: inherit; font-family: Helvetica, Arial, sans-serif;" class="">
                                                A list of your top performing campaigns and the number of leads added over the last 6 hours.
                                            </span>
                                        </p>
                                    </td>
                                </tr>
                                <tr style="background-color: #ffffff;">
                                    <td valign="top" style="padding: 24px 40px; background-color: #ffffff;">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                            <#list RECENT_CAMPAIGN_ROWS as RECENT_CAMPAIGN_ROW>
                                                <#if RECENT_CAMPAIGN_ROW_index == 0>
                                                    <tr>
                                                        <td style="background-color: #FFFFFF; border: 1px solid #979797; border-right: none; padding: 16px 32px;">
                                                            <a href="${RECENT_CAMPAIGN_ROW.campaignReportUrl}" style="color: ${PRIMARY_COLOR}; font-size: 16px; text-decoration: none;">
                                                                ${RECENT_CAMPAIGN_ROW.campaignName}
                                                            </a>
                                                        </td>
                                                        <td style="background-color: #FFFFFF; border: 1px solid #979797; border-left: none; padding: 16px 32px; text-align: right; width: 144px;">
                                                            <span style="color: #191919; font-size: 16px; font-weight: bold">
                                                                ${RECENT_CAMPAIGN_ROW.numOfLeads}
                                                            </span>
                                                        </td>
                                                    </tr>
                                                <#elseif RECENT_CAMPAIGN_ROW_index % 2 == 0>
                                                    <tr>
                                                        <td style="background-color: #FFFFFF; border: 1px solid #979797; border-right: none; border-top: none; padding: 16px 32px;">
                                                            <a href="${RECENT_CAMPAIGN_ROW.campaignReportUrl}" style="color: ${PRIMARY_COLOR}; font-size: 16px; text-decoration: none;">
                                                                ${RECENT_CAMPAIGN_ROW.campaignName}
                                                            </a>
                                                        </td>
                                                        <td style="background-color: #FFFFFF; border: 1px solid #979797; border-left: none; border-top: none; padding: 16px 32px; text-align: right; width: 144px;">
                                                            <span style="color: #191919; font-size: 16px; font-weight: bold">
                                                                ${RECENT_CAMPAIGN_ROW.numOfLeads}
                                                            </span>
                                                        </td>
                                                    </tr>
                                                <#else>
                                                    <tr>
                                                        <td style="background-color: #FAFAFA; border: 1px solid #979797; border-right: none; border-top: none; padding: 16px 32px;">
                                                            <a href="${RECENT_CAMPAIGN_ROW.campaignReportUrl}" style="color: ${PRIMARY_COLOR}; font-size: 16px; text-decoration: none;">
                                                                ${RECENT_CAMPAIGN_ROW.campaignName}
                                                            </a>
                                                        </td>
                                                        <td style="background-color: #FAFAFA; border: 1px solid #979797; border-left: none; border-top: none; padding: 16px 32px; text-align: right; width: 144px;">
                                                            <span style="color: #191919; font-size: 16px; font-weight: bold">
                                                                ${RECENT_CAMPAIGN_ROW.numOfLeads}
                                                            </span>
                                                        </td>
                                                    </tr>
                                                </#if>
                                            <#else>
                                            </#list>
                                        </table>
                                    </td>
                                </tr>
                                </#if>
                                <tr style="background-color: #ffffff;">
                                    <td id="layout-row-margin4310" valign="top" style="padding: 20px 40px; background-color: #ffffff;">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important; margin-bottom: 40px;">
                                            <tr id="layout-row4310" class="layout layout-row widget _widget_html style4310" style="">
                                                <td id="layout-row-padding4310" valign="top" style="padding: 0px;">
                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td id="html_div3633" width="610" align="left">
                                                                <a href="${LEAD_REPORT_URL}" target="_blank">
                                                                    <div class="button-wrapper" style="margin: 0; outline: none; padding: 0; text-align: center;">
                                                                        <span class="button-text" style="background-color: ${PRIMARY_COLOR}; border: none; border-radius: 100px; color: white; text-align: center; text-decoration:none; mso-hide:all; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; letter-spacing: 0.5px; font-weight: 500; padding: 13px 50px; display:inline-block; font-size: 1.2em;">View Lead Report</span>
                                                                    </div>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr style="background-color: #ffffff;">
                                    <td id="layout-row-margin5472" valign="top" style="padding: 0px; background-color: #ffffff;">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: initial !important;">
                                            <tr id="layout-row5472" class="layout layout-row widget _widget_text style5472" style="margin: 0; padding: 0; background-color: #e7e7e7;">
                                                <td id="layout-row-padding5472" valign="top" style="background-color: #e7e7e7; padding: 20px;">
                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size: 13px; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td id="text_div4578" class="td_text td_block" valign="top" align="left" style="line-height: 140%; color: inherit; font-size: 12px; font-weight: inherit; line-height: 1.4; text-decoration: inherit; font-family: Arial; mso-line-height-rule: exactly;">
                                                                <div style="line-height: 140%; margin: 0; outline: none; padding: 0; color: #999999; mso-line-height-rule: exactly; line-height: 1.4;" class="">
                                                                    <div style="margin: 0; outline: none; padding: 0; font-size: 12px; color: #999999;" class="">
                                                                        <div style="margin: 0; outline: none; padding: 0; color: #999999;" class="">
                                                                            <div style="margin: 0; outline: none; padding: 0; color: #999999;" class="">
                                                                                <div style="margin: 0; outline: none; padding: 0; color: #999999;" class="">
                                                                                    <div style="margin: 0; outline: none; padding: 0; color: #999999;" class="">
                                                                                        <p style="margin: 0; outline: none; padding: 0; color: #999999; font-size: inherit; font-weight: inherit; line-height: inherit; text-decoration: inherit; text-align: center;" class="">
																								<span style="color: #999999; font-size: inherit; font-weight: 400; line-height: inherit; text-decoration: inherit; font-family: Helvetica, Arial, sans-serif; font-style: normal;" class="">
																									<span style="color: #999999; font-size: 12px; font-weight: 400; line-height: inherit; text-decoration: inherit; font-family: Helvetica, Arial, sans-serif; font-style: normal;">
																										<span style="color: #999999; font-size: 12px; font-weight: 400; line-height: inherit; text-decoration: inherit; font-family: Helvetica, Arial, sans-serif; font-style: normal;">© ${CURRENT_YEAR} ${COPYRIGHT}</span>
																									</span>
																								</span><br style="color: #999999;" class="" />
                                                                                        </p>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <!--[if (gte mso 12)&(lte mso 15) ]> <style type="text/css" data-ac-inline="false"> #text_div4578, #text_div4578 div { line-height: 140% !important; }; </style> <![endif]-->
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>

</html>
