CREATE TYPE "user_level" AS ENUM (
  'normal',
  'upper',
  'high_upper',
  'high_end',
  'ultra'
);

CREATE TYPE "order_status" AS ENUM (
  'placed',
  'preparing',
  'on_way',
  'delivered'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "phone_number" varchar(50),
  "password_hash" varchar(255) NOT NULL,
  "address" text,
  "user_level" user_level NOT NULL,
  "country_code" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "countries" (
  "code" integer PRIMARY KEY,
  "name" varchar,
  "continent_name" varchar
);

CREATE TABLE "restaurants" (
  "id" integer PRIMARY KEY,
  "name" varchar,
  "address" text,
  "country_code" integer,
  "phone_number" varchar(50),
  "rating" decimal(3,2),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "food_items" (
  "id" integer PRIMARY KEY,
  "restaurant_id" integer,
  "name" varchar,
  "description" text,
  "price" decimal(10,2),
  "currency" varchar(10),
  "available" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" integer PRIMARY KEY,
  "user_id" integer,
  "total_price" decimal(10,2),
  "currency" varchar(10),
  "order_time" timestamp DEFAULT (now()),
  "delivery_address" text,
  "status" order_status
);

CREATE TABLE "order_details" (
  "id" integer PRIMARY KEY,
  "order_id" integer,
  "food_item_id" integer,
  "quantity" integer,
  "price" decimal(10,2)
);

CREATE TABLE "industries" (
  "id" integer PRIMARY KEY,
  "name" varchar,
  "description" text
);

CREATE TABLE "user_industries" (
  "user_id" integer,
  "industry_id" integer,
  "occupation" varchar
);

COMMENT ON TABLE "users" IS 'Stores user data, including authentication and personal details.';

COMMENT ON TABLE "user_industries" IS 'Links users to their respective industries and occupations.';

ALTER TABLE "users" ADD FOREIGN KEY ("country_code") REFERENCES "countries" ("code");

ALTER TABLE "restaurants" ADD FOREIGN KEY ("country_code") REFERENCES "countries" ("code");

ALTER TABLE "food_items" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("food_item_id") REFERENCES "food_items" ("id");

ALTER TABLE "user_industries" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_industries" ADD FOREIGN KEY ("industry_id") REFERENCES "industries" ("id");
